config/routes.rb
Threesquare::Application.routes.draw do

  root 'locations#index'
  resources :locations
end


#        Prefix Verb   URI Pattern                   Controller#Action
#          root GET    /                             locations#index
#     locations GET    /locations(.:format)          locations#index
#               POST   /locations(.:format)          locations#create
#  new_location GET    /locations/new(.:format)      locations#new
# edit_location GET    /locations/:id/edit(.:format) locations#edit
#      location GET    /locations/:id(.:format)      locations#show
#               PATCH  /locations/:id(.:format)      locations#update
#               PUT    /locations/:id(.:format)      locations#update
#               DELETE /locations/:id(.:format)      locations#destroy

app/models/location.rb
class Location < ActiveRecord::Base

	validates :name, :picture_url, :review, presence: true

	def snippet
		self.review.truncate(25)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/locations_controller.rb
class LocationsController < ApplicationController

	def show
		@location = Location.find_by_id(params[:id])
	end

	def index
		@locations = Location.all
	end

	def new
		@location = Location.new
	end

	def create
		@location = Location.new(location_params)
		@location.save
		redirect_to root_path
	end

	def edit
		@location = Location.find(params[:id])
	end

	def update
		@location = Location.find(params[:id])
		@location.update(location_params)
		redirect_to root_path
	end

	def destroy
		@location = Location.find(params[:id])
		@location.destroy
		redirect_to root_path
	end


	private
	def location_params
	  params.require(:location).permit(:name, :picture_url, :review)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Threesquare</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for @location do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br>
	<%= f.label :picture_url %>
	<%= f.text_field :picture_url %>
	<br>
	<%= f.label :review %>
	<%= f.text_field :review %>
	<br>
	<%= f.submit %>
<% end %>

app/views/locations/edit.html.erb
<h2> Edit this Location: <%= @location.name %></h2>

<%= render "form" %>

app/views/locations/index.html.erb
<h1>Welcome to The Threesquare</h1>

<%= link_to "Add a New Location!", new_location_path %>

<ul>
	<% @locations.each do |location| %>
		<li>
			<img src="<%=location.picture_url%>" height="100" width="100">
			<%= link_to location.name, location %>:&nbsp
			<%= location.snippet %>
		</li>
		<br>
	<% end %>
</ul>

app/views/locations/new.html.erb
<h1>Create a New Location</h1>

<%= render "form" %>

app/views/locations/show.html.erb
<h1><%= @location.name %></h1>
<%= link_to "HOME", root_url %>
<%= link_to "EDIT", edit_location_path(@location) %>

<%= link_to 'DELETE', @location, method: :delete, data: {confirm: 'Are you sure you want to delete this location?'} %>


<p>
	<%= @location.review %>
</p>
<img src="<%= @location.picture_url %>">
<br>